name: main
on: [push]
strategy:
  matrix:
    os: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: make
      - uses: romgrk/publish-to-github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
