name: main
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
      - uses: mikeal/publish-to-github-action@e5a27bb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
      - uses: mikeal/publish-to-github-action@e5a27bb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
      - uses: mikeal/publish-to-github-action@e5a27bb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
