name: main
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: git status
